# Fuzz Testing Configuration for go-fsdt
# This file contains configuration parameters for fuzz testing workflows

# Default fuzz test parameters
defaults:
  fuzz_duration: 10        # minutes
  parallel_workers: 16     # number of parallel workers
  timeout_buffer: 2        # minutes buffer for timeout

# Fuzz test configurations
tests:
  FuzzFolderCreation:
    description: "Tests folder creation with various inputs including edge cases"
    default_duration: 5
    max_duration: 30
    min_workers: 4
    max_workers: 32
    
  FuzzFileOperations:
    description: "Tests file operations with various content types and modes"
    default_duration: 8
    max_duration: 30
    min_workers: 4
    max_workers: 32
    
  FuzzLinkOperations:
    description: "Tests link operations with various target types"
    default_duration: 5
    max_duration: 30
    min_workers: 4
    max_workers: 32
    
  FuzzFolderOperations:
    description: "Tests complex folder operations and cloning"
    default_duration: 10
    max_duration: 45
    min_workers: 4
    max_workers: 24
    
  FuzzDiffOperations:
    description: "Tests diff operations with various folder structures"
    default_duration: 12
    max_duration: 60
    min_workers: 4
    max_workers: 24
    
  FuzzEdgeCases:
    description: "Tests various edge cases and error conditions"
    default_duration: 8
    max_duration: 30
    min_workers: 4
    max_workers: 32
    
  FuzzSerialization:
    description: "Tests serialization and deserialization edge cases"
    default_duration: 6
    max_duration: 25
    min_workers: 4
    max_workers: 32
    
  FuzzMemoryStress:
    description: "Tests memory allocation and stress scenarios"
    default_duration: 15
    max_duration: 60
    min_workers: 4
    max_workers: 16

# Workflow schedules
schedules:
  daily:
    cron: "0 2 * * *"      # Daily at 2 AM UTC
    duration: 5             # 5 minutes per test
    workers: 8              # 8 workers for daily runs
    
  weekly:
    cron: "0 3 * * 0"      # Weekly on Sunday at 3 AM UTC
    duration: 15            # 15 minutes per test
    workers: 12             # 12 workers for weekly runs
    
  intensive:
    cron: "0 4 * * 0"      # Weekly on Sunday at 4 AM UTC
    duration: 30            # 30 minutes per test
    workers: 16             # 16 workers for intensive runs

# Resource limits
limits:
  max_total_duration: 480  # 8 hours total
  max_memory_per_worker: "512Mi"
  max_cpu_per_worker: "1.0"
  max_parallel_workers: 32

# Artifact retention
retention:
  fuzz_corpus: 90          # days
  fuzz_logs: 30            # days
  coverage_reports: 90     # days
  performance_results: 30  # days
